### ISSUE TITLE
README TLDR

### ISSUE THREAD

**Issue by jgarte** [74th/xonsh-direnv#13]
Hi, would it be possible to give a TLDR in the README of how exactly this supports direnv with xonsh.

I'm reading the code now to find out.

**Comment by jgarte** [comment]
I see that you export some json from direnv here and then pass it to some xonsh environment call:

```python
r = $(direnv export json)
```

**Comment by con-f-use** [comment]
Yes, the key part is [this](https://github.com/74th/xonsh-direnv/blob/master/xontrib/direnv.xsh#L14):
```python
        lines = json.loads(r)
        for k, v in lines.items():
            if v is None:
                del __xonsh__.env[k]
            else:
                __xonsh__.env[k] = v
```
`direnv` istself supports exporting the environment changes it makes to JSON, and in these lines those changes get put into the xonsh environment. I don't think this belongs in the readme, because it is not interesting to the end-user, only to developers.
